### ISSUE TITLE
Can't parse recipe URL

### ISSUE THREAD

**Issue by Desy10140** [julianpoy/RecipeSage-selfhost#95]
Updated to self host 3.0.1 and when adding a recipe URL it doesn't populate any information.

I haven't changed my compose except to update the version of the images, not sure what broke.

[recipesage_compose.txt](https://github.com/user-attachments/files/21332053/recipesage_compose.txt)
[_recipesage_api_logs.txt](https://github.com/user-attachments/files/21332054/_recipesage_api_logs.txt)

Please do the following and check the boxes before filing
[ X] I have attached my docker-compose.yaml to the issue
[X ] I have attached the logs for my api container to the issue
[ X] My issue is related to this selfhost repo, not the main tracker for RecipeSage [here](https://github.com/julianpoy/RecipeSage/issues)

**Comment by Desy10140** [comment]
**Troubleshooting Steps Performed**
I have gone through an extensive troubleshooting process. Here is a summary of everything I've tried:

**Fixed Classifier DNS:** 
The classifier container initially had a `DNS` error `(ENOTFOUND tfhub.dev)`. I resolved this by adding a dns block to its service definition in the `docker-compose.yml` file.

**Enabled and Configured Services:** 
The api container was failing because the browserless service was not configured. I enabled the browserless and ingredient-instruction-classifier services, corrected the `INGREDIENT_INSTRUCTION_CLASSIFIER_URL` to use the proper container name, and added them to the api service's `depends_on` list.

**Added Database Healthcheck:** 
I encountered a database race condition `(P1017 error)`. I resolved this by adding a healthcheck to the postgres service and updating the api service to wait for the database to be healthy before starting.

**Environment Variable Format:** 
I reformatted all environment sections in the `docker-compose.yml` to use the `KEY: VALUE` (map) format.

**Used an .env File:** 
To ensure the environment variables were being loaded correctly, I moved the `BROWSERLESS_HOST`, `BROWSERLESS_PORT`, and `INGREDIENT_INSTRUCTION_CLASSIFIER_URL` variables out of the `docker-compose.yml` and into a separate .env file.

**Current Status & Logs**
Despite all these corrections, the recipe parsing functionality still fails. The api container logs show that the application successfully connects to the database and serves existing data, but when the /clip endpoint is called, it still throws the same error as it did at the beginning of this process.

**Key Error from api container log:**

```
Error: BROWSERLESS_HOST, BROWSERLESS_PORT, and BROWSERLESS_TOKEN must be defined in environment variables to enable browserless
    at clipRecipeUrlWithPuppeteer (/app/packages/util/server/src/general/clip.ts:63:13)
    at clipUrl (/app/packages/util/server/src/general/clip.ts:203:35)
    ...
```
It seems the `api:v3.0.1` container is unable to read these specific environment variables, regardless of the method used to provide them.

My last YAML config with NO ENV file.
```
services:
  proxy:
    container_name: recipesage_proxy
    image: julianpoy/recipesage-selfhost-proxy:v4.0.0
    ports:
      - "7270:80"
    depends_on:
      - static
      - api
      - pushpin
    restart: unless-stopped
  static:
    container_name: recipesage_static
    image: julianpoy/recipesage-selfhost:static-v3.0.1
    restart: unless-stopped
  api:
    container_name: recipesage_api
    image: julianpoy/recipesage-selfhost:api-v3.0.1
    depends_on:
      postgres:
        condition: service_healthy
      typesense:
        condition: service_started
      pushpin:
        condition: service_started
      browserless:
        condition: service_started
      ingredient-instruction-classifier:
        condition: service_started
    command: sh -c "npx prisma migrate deploy; npx nx seed prisma; npx ts-node --swc --project packages/backend/tsconfig.json packages/backend/src/bin/www"
    environment:
      STORAGE_TYPE: filesystem
      FILESYSTEM_STORAGE_PATH: /rs-media
      NODE_ENV: selfhost
      VERBOSE: "false"
      VERSION: selfhost
      POSTGRES_DB: recipesage_selfhost
      POSTGRES_USER: recipesage_selfhost
      POSTGRES_PASSWORD: REDACTED # SANITIZED_SECRET
      POSTGRES_PORT: "5432"
      POSTGRES_HOST: recipesage_postgres
      POSTGRES_SSL: "false"
      POSTGRES_LOGGING: "false"
      DATABASE_URL: "postgresql://recipesage_selfhost:REDACTED@postgres:5432/recipesage_selfhost" # SANITIZED_SECRET
      GCM_KEYPAIR:
      SENTRY_DSN:
      GRIP_URL: http://pushpin:5561/
      GRIP_KEY: changeme
      SEARCH_PROVIDER: typesense
      TYPESENSE_NODES: '[{"host": "typesense", "port": 8108, "protocol": "http"}]'
      TYPESENSE_API_KEY: recipesage_selfhost
      STRIPE_SK:
      STRIPE_WEBHOOK_SECRET:
      BROWSERLESS_HOST: recipesage_browserless
      BROWSERLESS_PORT: "3000"
      INGREDIENT_INSTRUCTION_CLASSIFIER_URL: http://recipesage_classifier:3000/
      OPENAI_API_KEY: REDACTED # SANITIZED_SECRET
    volumes:
      - apimedia:/rs-media
    restart: unless-stopped
  typesense:
    container_name: recipesage_typesense
    image: typesense/typesense:0.24.1
    volumes:
      - typesensedata:/data
    command: "--data-dir /data --api-key=recipesage_selfhost --enable-cors"
    restart: unless-stopped
  pushpin:
    container_name: recipesage_pushpin
    image: julianpoy/pushpin:2023-09-17
    entrypoint: /bin/sh -c
    command:
      - 'sed -i "s/sig_key=changeme/sig_key=$$GRIP_KEY/" /etc/pushpin/pushpin.conf && echo "* $${TARGET},over_http" > /etc/pushpin/routes && pushpin --merge-output'
    environment:
      GRIP_KEY: changeme
      TARGET: api:3000
    restart: unless-stopped
  postgres:
    container_name: recipesage_postgres
    image: postgres:16
    environment:
      POSTGRES_DB: recipesage_selfhost
      POSTGRES_USER: recipesage_selfhost
      POSTGRES_PASSWORD: REDACTED # SANITIZED_SECRET
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipesage_selfhost -d recipesage_selfhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  browserless:
    container_name: recipesage_browserless
    image: ghcr.io/browserless/chromium:v2.24.3
    environment:
      MAX_CONCURRENT_SESSIONS: "3"
      MAX_QUEUE_LENGTH: "10"
    restart: unless-stopped
  ingredient-instruction-classifier:
    container_name: recipesage_classifier
    image: julianpoy/ingredient-instruction-classifier:1.4.11
    environment:
      SENTENCE_EMBEDDING_BATCH_SIZE: "200"
      PREDICTION_CONCURRENCY: "2"
    restart: unless-stopped
    dns:
      - "8.8.8.8"
      - "1.1.1.1"

volumes:
  apimedia:
    driver: local
  typesensedata:
    driver: local
  postgresdata:
    driver: local
```

**Comment by Desy10140** [comment]
Tried with the latest `API` & `STATIC` builds on dockerhub: `3.0.13` but got `Error: Cannot find module './www'`

**SOLVE**
Hard coded to `static-v3.0.10` & `api-v3.0.10` from dockerhub tt seems this version doesn't have the `browserless` or `./www` issues.

**Comment by julianpoy** [comment]
The latest version of RecipeSage supported for selfhost is v3.0.10.

[The note at the top of the Dockerfile indicates compatibility](https://github.com/julianpoy/RecipeSage-selfhost/blob/main/docker-compose.yml#L1). Glad to hear you got it solved, though!
